# Generated by Django 4.2.4 on 2023-08-05 06:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.FileField(upload_to='pictures/')),
                ('pic_type', models.CharField(choices=[('wedding', 'Wedding'), ('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('party', 'Party'), ('cradle', 'Cradle')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('theme', models.CharField(max_length=50, null=True)),
                ('cake', models.CharField(max_length=50, null=True)),
                ('cradle', models.CharField(max_length=50, null=True)),
                ('decoration', models.CharField(max_length=50, null=True)),
                ('entertainment', models.CharField(max_length=50, null=True)),
                ('balloons', models.CharField(max_length=50, null=True)),
                ('guest', models.IntegerField()),
                ('date', models.DateField()),
                ('planner', models.CharField(blank=True, max_length=100, null=True)),
                ('booked_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=True)),
                ('location', models.CharField(max_length=50)),
                ('suggest', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pictureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_name', models.CharField(max_length=50)),
                ('pic', models.FileField(upload_to='pictures/')),
                ('pic_type', models.CharField(choices=[('theme', 'Theme'), ('cradle', 'Cradle'), ('cake', 'Cake'), ('decoration', 'Decoration'), ('entertainment', 'Entertainment'), ('balloons', 'Balloons')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='userData1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vname', models.CharField(max_length=100)),
                ('vmobile', models.CharField(max_length=15)),
                ('vemail', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
